unique_ids:
  assets:
    standard-page.html: QZCYUN4VEJNRKZKXSD45GVKMKFYKGV3A
    theme.css: NSIB4EJL6MVN5ZPDN3FGLIUPWGRWQ3WL
  forms:
    up_dataant_info: 3FQ3CJRKOQSB5HUV34YELV4MZ7RWBLP3
    up_dataant_info.RowTemplate1: '1761017786770931612468588.2498'
  modules: {}
  scripts: {}
  server_modules: {}
