unique_ids:
  assets:
    standard-page.html: QZCYUN4VEJNRKZKXSD45GVKMKFYKGV3A
    theme.css: NSIB4EJL6MVN5ZPDN3FGLIUPWGRWQ3WL
  forms:
    Form1: 3FQ3CJRKOQSB5HUV34YELV4MZ7RWBLP3
  modules: {}
  scripts: {}
  server_modules: {}
